### ISSUE TITLE
500 error on Generate Names

### ISSUE THREAD

**Issue by RomanMovchan2105** [dravicenna/ai-petnamer#1]
Hi!

I get 500 error on Generate Names with params
csrfmiddlewaretoken: BlvytJj71cscEMZWi8i4gBleswFcPMSaxInz7LkqqEn0uhE8uGyZEZXP3SvbrnHR
pet_type: cat
gender: female
color: black
origin: Irish
personality_traits: friendly
historical_themes: none

can you check this?

**Comment by dravicenna** [comment]
Hey! Yes, it was a problem with my DB. Now it's working. Thank you for request!
